ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views

app_name="cart"

urlpatterns = [
    path('addtocart/<n>',views.addtocart,name='addtocart'),
    path('cartview',views.cartview,name='cartview'),
    path('cart_remove/<n>',views.cart_remove,name='cart_remove'),
    path('full_remove/<n>',views.full_remove,name='full_remove'),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views

app_name="search"

urlpatterns = [
    path('search',views.search,name='search'),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"
urlpatterns = [
    path('',views.allcategories,name='allcategories'),
    path('categorydetail/<p>',views.categorydetail,name='categorydetail'),
    path('productdetail/<p>',views.productdetail,name='productdetail'),
    path('register',views.register,name='register'),
    path('login',views.user_login,name='login'),
    path('logout',views.user_logout,name='logout'),
]

ecommerce/cart/models.py
from django.db import models
from shop.models import  Product
from django.contrib.auth.models import User
from django.http import HttpResponse
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=0)
    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.product.name
    def subtotal(self):
        return self.quantity*self.product.price
class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField(default=0)
    order_status=models.CharField(max_length=20,default="pending")
    delivery_status=models.CharField(max_length=20,default="pending")
    ordered_date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
class Account(models.Model):
    acctnum=models.CharField(max_length=20)
    accttype=models.CharField(max_length=20)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from shop.models import Product
from cart.models import Cart,Account,Order
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
# Create your views here.
@login_required
def cartview(request):
    total=0
    u=request.user
    try:
       c=Cart.objects.filter(user=u)
       for i in c:
          total+=i.quantity*i.product.price
    except:
        pass
    return render(request,'cart.html',{'d':c,'t':total})
@login_required
def addtocart(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if (p.stock>0):
               c.quantity+=1
               c.save()
               p.stock -= 1
               p.save()
    except:
        if (p.stock>0):
            c=Cart.objects.create(product=p,user=u,quantity=1)
            c.save()
            p.stock-=1
            p.save()
    return cartview(request)
@login_required
def cart_remove(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
         c = Cart.objects.get(user=u, product=p)
         if (c.quantity>1):
           c.quantity-=1
           c.save()
           p.stock += 1
           p.save()
         else:
             c.delete()
             p.stock += 1
             p.save()
    except:
        pass
    return cartview(request)
@login_required
def full_remove(request,n):
    p = Product.objects.get(name=n)
    u = request.user
    try:
         c = Cart.objects.get(user=u, product=p)
         c.delete()
         p.stock += c.quantity
         p.save()
    except:
        pass
    return (cartview(request))


@login_required
def orderform(request):
    if (request.method=="POST"):
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0 #total bill amount
        for i in c:
            total+=i.quantity*i.product.price
        try:
            ac=Account.objects.get(acctnum=n)#to retrive the acctobject
            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in c:
                    o=Order.objects.create(user=u,product=i.product,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                c.delete()
                msg="your order placed successfully"
                return render(request,'orderdetail.html',{'m':msg})
            else:
                msg="insufficient amount.you can't place order"
                return render(request,'orderdetail.html',{'m':msg})


        except:
            pass
    return render(request,'orderform.html')
@login_required
def orderview(request):
    u=request.user
    f=Order.objects.filter(user=u)

    return render(request,'orderview.html',{'o':f,'u':u.username})

ecommerce/search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def search(request):
    s=None
    q=""
    if (request.method=="POST"):
        q=request.POST['q']
        print("query",q)
        if q:
            s=Product.objects.filter(Q(name__icontains=q)|Q(desc__icontains=q))
    return render(request,'search.html',{'c':q,'b':s})

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@1,200&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
<header><center>
    <img src="{% static 'images/ecomlogo.png' %}" height="100px" width="100px"></center>
</header>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-top:30px;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcategories' %}">Home</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All Categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:categorydetail' i.name %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
          {% if user.is_authenticated %}

          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% if user.is_superuser == False %}
          <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"><sup class="ms-2">{{count}}</sup></i></a>
        </li>
          <li class="nav-item">
          <a class="nav-link fs-5" href="{% url 'cart:orderview' %}">your orders</a>
        </li>
          {% endif %}
          {% else %}
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:login' %}">Login</a>
        </li>
         {% endif %}
      </ul>
    </div>
  </div>
    <form class="d-flex" method="POST" action="{% url 'search:search' %}">
        {% csrf_token %}
      <input class="form-control me-2" name='q' type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</nav>
{% block content %}
{% endblock %}

<footer>
    <div class="footer">

            <p><b><i class="fa-solid fa-copyright"></i>my shop pvt ltd. All Rights Reserved</b></p>

    </div>

        </footer>

</body>
</html>

ecommerce/templates/cart.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
    <div class="row text-center fs-5">
        <h4 class="text-center">Shopping Cart</h4>
        <div class="col-8"><table class="table table-bordered"><tr><th colspan="5">Cart Items</th></tr>

        {% for i in d %}
        <tr><td>
            <img src="{{ i.product.image.url }}" height="200px" width="200px">


        </td><td><h6>{{i.product.name}}</h6></td>
        <td><h6>product id:{{i.product.id}}</h6>
        <h6>Unit Price:{{i.product.price}}</h6>
        <h6>Quantity:{{i.quantity}}*{{i.product.price}}</h6>
        <td>Subtotal:{{i.subtotal}}</td>
        <td>
            {% if i.product.stock > 0 %}<a href="{% url 'cart:addtocart' i.product.name %}"><i class="fa-solid fa-circle-plus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a>
        {% else %}
        <a href="{% url 'cart:cart_remove' i.product.name %}"><i class="fa-solid fa-circle-minus text-secondary fs-5"></i></a>
        <a href="{% url 'cart:full_remove' i.product.name %}"><i class="fa-solid fa-trash text-secondary fs-5"></i></a></td></tr>
        {% endif %}
            {% endfor %}
            </table></div>
        <div class="col-4" style="position:relative;"><table class="table table-bordered"><tr><th colspan="6">Check Out</th></tr>
        <tr><td>Total:{{t}}</td></tr></table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;left:10px;">Place Order</a>
        <a href="{% url 'shop:allcategories' %}" class="btn btn-danger" style="position:absolute;right:10px;" >Continue Shopping</a>
            </div>
    </div>
</div>
{% endblock %}

</body>
</html>

ecommerce/templates/category.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div>
<img src="{% static 'images/banner1.png' %} " height="450px;" width="100%">
</div>
<div class="container-fluid mt-3" style="margin-bottom:100px;">
    <h3 class="text-center fw-bold">Our Collections</h3>
    <p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum</p>

</div>
<div class="container" style="margin-bottom:100px;">
<div class="row">
{% for i in p %}
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:300px;width:100%;">
            <div class="card-body">
                <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted"></h6>
                <p class="card-text"></p>
                <a href="{% url 'shop:categorydetail' i.name %}" class="btn btn-danger" style="position:relative;left:35%;">products</a>
            </div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

</body>
</html>

ecommerce/templates/categorydetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<img src="{{m.image.url}}"style="height:400px;width:100%">
<div class="container-fluid mt-3" style="margin-bottom:100px;">
<h3 class="text-center fw-bold">{{m.name}}</h3>
<p style="text-align:justify;line-height:2;">{{m.desc}}</p>
</div>
<div class="container" style="margin-bottom:100px;">
<div class="row">
{% for i in c %}
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:300px;width:100%;">
            <div class="card-body">
                <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted text-center fw-bold">{{i.price}}</h6>
                <p class="card-text"></p>
                <a href="{% url 'shop:productdetail' i.name %}" class="btn btn-danger" style="position:relative;left:35%;">Details</a>
            </div>
        </div>
    </div>
{% endfor %}
{% endblock %}
</body>
</html>

ecommerce/templates/login.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
<h2>Login</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter name">
</div>
<div class="mb-3">
    <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
  </div>

<div class="mb-3">
    <input type="submit" class="form-control btn btn-primary"></input>
  </div>
</form>

{% endblock %}
    </center>
</body>
</html>

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
</div>
<h4 class="text-center text-success">{{m}}</h4>
<h4 class="text-center text-danger">Thank You....</h4>
<h4 class="text-center"><a href="{% url 'shop:allcategories' %}">Continue Shopping</a></h4>


{% endblock %}

ecommerce/templates/orderform.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container">
<center>
    <h1>OrderForm</h1>
    <form method="POST" >
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Address</label>
  <input type="text" class="form-control" name="a" placeholder="enter address">
</div>
        <div class="mb-3">
  <label class="form-label">Phone</label>
  <input type="number" class="form-control" name="p" placeholder="enter phone">
</div>
        <div class="mb-3">
  <label class="form-label">Acctnumber</label>
  <input type="number" class="form-control" name="n" placeholder="enter acctnumber">
</div>
        <div class="mb-5">
    <input type="submit" class="form-control btn btn-primary"></input>
  </div>
</form></div>




</center>
{% endblock %}


</body>
</html>

ecommerce/templates/orderview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row mt-5">
        <h1 class="text-center text-danger">Name of the Customer:{{u}}</h1>
{% for i in o %}
        <div class="col-sm-4 mt-3" style="margin:100px;">
            <img src="{{i.product.image.url}}" height="200px;" width="200px;">
        </div>
  <div class="col-sm-5">
<h4>product_name:{{i.product.name}}</h4>
<h4>product_price:{{i.product.price}}</h4>
<h4>delivery_address:{{i.address}}</h4>
<h4>phone:{{i.phone}}</h4>
<h4>no_of_items:{{i.no_of_items}}</h4>
<h5>ordered on:{{i.ordered_date}}</h5>
<h5>delivery_status:{{i.delivery_status}}</h5></div>
    </div>
{% endfor %}
{% endblock %}

ecommerce/templates/productdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="container-fluid">
<div class="row">
<img src="{{h.image.url}}"style="height:300px;width:50%">
<div class="col-sm-6" >

          <h5 class="fw-bold">{{h.name}}</h5>
           <h6>price:{{h.price}}</h6>
           <p style="text-align:justify;line-height:2;">{{h.desc}}</p>
            <p>stock:{{h.stock}}</p>
            {% if user.is_superuser == True %}
                {% if h.stock == 0 %}
                   <h2>Out of Stock</h2>
                   <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
                {% else %}
                  <h2>product in stock</h2>
                  <a href="{% url 'admin:index' %}" class="btn btn-danger mt-5">ADD STOCK</a>
                {% endif %}
            {% else %}
              {% if h.stock == 0 %}
                <h2>Out of Stock</h2>
              {% else %}
                <a href="{% url 'cart:addtocart' h.name %}" class="btn btn-danger">Add to Cart</a>
              {% endif %}
            {% endif %}

        </div>
    </div></div>

{% endblock %}
    </div>

</body>
</html>

ecommerce/templates/register.html
<!DOCTYPE html>

{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
<h1>Register </h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

<div class="mb-3">
  <label class="form-label">Username</label>
  <input type="text" class="form-control" name="u" placeholder="enter name">
</div>
<div class="mb-3">
    <label  class="form-label">Password</label>
  <input type="password" class="form-control" name="p" placeholder="enter password">
  </div>
<div class="mb-3">
    <label class="form-label">confirm password</label>
  <input type="password" class="form-control" name="c" placeholder="enter password again">
  </div>
    <div class="mb-3">
    <label class="form-label">Email</label>
  <input type="email" class="form-control" name="e" placeholder="enter email" >
  </div>
    <div class="mb-3">
    <label class="form-label">First name</label>
  <input type="text" class="form-control" name="f" placeholder="enter first name">
  </div>
    <div class="mb-3">
    <label class="form-label">last name</label>
  <input type="text" class="form-control" name="l" placeholder="enter last name">
  </div>

<div class="mb-5">
    <input type="submit" class="form-control btn btn-primary"></input>
  </div>
</form>
{% endblock %}
    </center>

</body>
</html>

ecommerce/templates/search.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<center>
<div class="container" style="margin-bottom:100px;">
<div class="row">
    {% if b %}
    <h3>product details</h3>
    <h5>you have searched for query {{c}} </h5>
    {% for i in b %}
    <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
            <img src="{{i.image.url}}" style="height:300px;width:100%;">
            <div class="card-body">
                <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{i.price}}</h6>
                <a href="{% url 'shop:productdetail' i.name %}" class="btn btn-danger" style="position:relative;">Details</a>

            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <b><p>No Results Found</p></b>
    {% endif %}
</center>

{% endblock %}


</body>
</html>